### ISSUE TITLE
Mouse cursor dont move between monitors in window mode

### ISSUE THREAD

**Issue by cgize** [sbritorodr/df-sdl12-compat#3]
I've using the gdrive version, after change to this version i cant move my mouse between monitors in window mode

**Comment by sbritorodr** [comment]
Hello, I am sorry but this fork isn't made for developing and improving SDL-compat, but just provide stable builds for SDL-compat for myself and share it to the community. Also, I don't have multiple monitors, so I can't help you either. 

The unwritten rule of programming is "Don't change anything that works". If you find the google drive version better it's not a bad idea to keep using it.

However, thanks for notifying the bug

**Comment by sbritorodr** [comment]
That being said. Go try out any configuration launch parameters listed at the README.md
